version: "3"

services:
  #Persistent database
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: nan
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: nan_db
      TZ: Europe/London
    networks:
      postgres_net:
        ipv4_address: 172.20.1.4

  backend:
    container_name: backend-server
    ports:
      - "443:443"
    environment:
      PORT: 443
      DB_URL: postgres://nan:supersecret@postgres:5432/nan_db
      ENV: production
      BCRYPT_SALT_ROUNDS: 12
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; npm run setup_db && npm run populate_db && npm run start'
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      postgres_net:
        ipv4_address: 172.20.1.8

networks:
  postgres_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24

volumes:
  postgres-data: